/**
 * Created by argulworm on 6/29/17.
 */

dt.mapconst = {
    TILE_CORRIDOR: 1,
    TILE_ROOMFLOOR: 2,
    TILE_MONSTER: 3,

    TILE_START_LOOT: 4,
    TILE_EQUIPMENT: 5,
    TILE_POTION: 6,
    TILE_SCROLL: 7,
    TILE_END_LOOT: 8,

    TILE_TRAP: 9,
    TILE_TRAP_PERSISTENT: 10,

    TILE_STAIR_UPWARD: 100,
    TILE_STAIR_DOWNWARD: 101,

    TILE_PASS: 1000,

    TILE_WALL: 1001,
    TILE_TREASURE: 1002,
    TILE_MONSTER_AVOID: 1100,
    TILE_TRAP_AVOID: 1101,
    TILE_TREASURE_AVOID: 1102,

    TILE_NOPASS: 2000
};