/**
 * Created by argulworm on 6/29/17.
 */

dt.mapconst = {
    TILE_CORRIDOR: 1,
    TILE_ROOMFLOOR: 2,
    TILE_MONSTER: 3,
    TILE_EQUIPMENT: 4,
    TILE_POTION: 5,
    TILE_SCROLL: 6,
    TILE_TRAP: 7,
    TILE_TRAP_PERSISTENT: 8,

    TILE_STAIR_UPWARD: 100,
    TILE_STAIR_DOWNWARD: 101,

    TILE_PASS: 1000,

    TILE_WALL: 1001,
    TILE_TREASURE: 1002,
    TILE_MONSTER_AVOID: 1100,
    TILE_TRAP_AVOID: 1101,
    TILE_TREASURE_AVOID: 1102,

    TILE_NOPASS: 2000
};