/**
 * Created by argulworm on 6/29/17.
 */

dt.mapconst = {
    TILE_WALL: 0,
    TILE_CORRIDOR: 1,
    TILE_ROOMFLOOR: 2,
    TILE_MONSTER: 3,
    TILE_TREASURE: 4,
    TILE_EQUIPMENT: 5,
    TILE_POTION: 6,
    TILE_SCROLL: 7,
    TILE_TRAP_HIDDEN: 8,

    TILE_MONSTER_AVOID: 100,
    TILE_TRAP_UNCOVER: 101,

    TILE_STAIR_UPWARD: 200,
    TILE_STAIR_DOWNWARD: 201
};