/**
 * Created by argulworm on 7/6/17.
 */

dt.behaviorCode = {
    DEFEATED: 'DEFEATED',
    ENTER_TOWER: 'ENTER_TOWER',
    LEAVE_TOWER: 'LEAVE_TOWER',
    ENTER_MAP: 'ENTER_MAP',
    LEAVE_MAP: 'LEAVE_MAP',
    MOVE: 'MOVE',
    HESITATE_POSITIVE: 'HESITATE_POSITIVE',
    HESITATE_NEGATIVE: 'HESITATE_NEGATIVE',
    LOOT_EQUIPMENT: 'LOOT_EQUIPMENT',
    LOOT_ITEM: 'LOOT_ITEM',
    OPEN_TREASURE_BOX: 'OPEN_TREASURE_BOX',
    ANIM_TREASURE_BOX_CONTENT: 'ANIM_TREASURE_BOX_CONTENT',
    GET_TREASURE_LOOTS: 'GET_TREASURE_LOOTS',
    OPEN_DOOR: 'OPEN_DOOR',
    DISARM_TRAP: 'DISARM_TRAP',
    TRIGGER_TRAP: 'TRIGGER_TRAP',
    RAID_MONSTER: 'RAID_MONSTER',
    ENTER_BATTLE: 'ENTER_BATTLE',
    LEAVE_BATTLE: 'LEAVE_BATTLE',

    UPDATE_MAP: 'UPDATE_MAP'
};